// <auto-generated />
using JedoxTranslator.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JedoxTranslator.Core.Data.Migrations
{
    [DbContext(typeof(TranslationDbContext))]
    partial class TranslationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JedoxTranslator.Core.Models.SourceText", b =>
                {
                    b.Property<string>("SID")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SID");

                    b.ToTable("SourceTexts");

                    b.HasData(
                        new
                        {
                            SID = "welcome_message",
                            Text = "Welcome to Jedox Translator"
                        },
                        new
                        {
                            SID = "goodbye_message",
                            Text = "Goodbye"
                        });
                });

            modelBuilder.Entity("JedoxTranslator.Core.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LangId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SID")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SID", "LangId")
                        .IsUnique();

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LangId = "de-DE",
                            SID = "welcome_message",
                            TranslatedText = "Willkommen bei Jedox Translator"
                        },
                        new
                        {
                            Id = 2,
                            LangId = "de-DE",
                            SID = "goodbye_message",
                            TranslatedText = "Auf Wiedersehen"
                        });
                });

            modelBuilder.Entity("JedoxTranslator.Core.Models.Translation", b =>
                {
                    b.HasOne("JedoxTranslator.Core.Models.SourceText", "SourceText")
                        .WithMany("Translations")
                        .HasForeignKey("SID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceText");
                });

            modelBuilder.Entity("JedoxTranslator.Core.Models.SourceText", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
